:_module-type: PROCEDURE

[id="proc_extending-the-spelling-rule_{context}"]
= Extending the *Spelling* rule

Consider extending the *Spelling* rule in the link:{repository-url}[{repository-name} repository] when:

* Missing words in the Vale dictionary are causing *Spelling* errors 
* Adding the word will benefit to other projects. For example: product and tool names, common terms specific to the software industry.

When the word is too specific to benefit to other projects, consider xref:end-user-guide:creating-a-vocabulary-for-a-project.adoc[].

.Prerequisites

* xref:end-user-guide:getting-started-with-vale.adoc[]
* xref:end-user-guide:understanding-vale-output.adoc[]
* xref:end-user-guide:defining-a-vale-onboarding-strategy.adoc[]


.Procedure

. Edit the `.vale/styles/RedHat/Spelling.yml` file and add the missing word to the `filters` list. A `filter` is a case-sensitive regular expression specifying words to ignore during spell checking.
+
.Excerpt of the *Spelling* rule
[source,yaml]
----
extends: spelling
message: "Did you really mean '%s'?"
level: error
filters:
  - '\.NET'
  - 'Dev Workspace'
  - 'I/O'
  - "[dD]evfile"
  - "[sS]harding"
  - "Let\'s Encrypt"
  - adoc
  - Ansible
  - Antora
  - API
  - AsciiDoc
----

. Edit the `.vale/fixtures/RedHat/Spelling/testvalid.adoc` file and add the missing word in a new line.

. Optionally, edit the `.vale/fixtures/RedHat/Spelling/testinvalid.adoc` file and add an undesired form of the missing word in a new line.

.Verification

. Run the `vale` command on a content file containing the word which was missing.
+
[subs="+quotes,+attributes"]
----
$ cd .vale/fixtures/RedHat/Spelling/
$ vale .
----

. Vale should:
+
* Report no error for the new term in the `testvalid.adoc` file
* Optionally, report an error for the new term in the `testinvalid.adoc` file

. Run only the _Spelling_ rule on your content.
+
[subs="+quotes,+attributes"]
----
$ vale --config=.vale/fixtures/RedHat/Spelling/ _<content files>_
----

.Additional resources

* link:https://docs.errata.ai/vale/styles#spelling[Vale documentation - Spelling]

