:navtitle: Passive voice
:keywords: reference, rule, PassiveVoice

= Passive Voice

Avoid the passive voice where possible. Active voice focuses on the performer of the action and is often clearer, shorter, and more direct than the passive voice.

According to the {ibmsg}, the passive voice is acceptable in the following situations:

* When the system performs the action
* When it is more appropriate to focus on the receiver of the action
* When you want to avoid blaming the user for an error, such as in an error message
* When the information is clearer in the passive voice
* When the information requires the passive voice, for example, glossary definitions

According to the {ssg}, you can use the passive voice in prerequisites.

.Additional resources

* link:{ssg-url}#prerequisites[{ssg} - Prerequisites]
* link:{ibmsg-url-print}[{ibmsg-print} - Voice, p.35]
* link:{ibmsg-url}?topic=grammar-verbs#voice[{ibmsg} - Voice]
* link:{repository-url}blob/main/.vale/styles/RedHat/PassiveVoice.yml[`PassiveVoice.yml` source code]
