:_module-type: CONCEPT

[id="con_understanding-vale-output_{context}"]
= Understanding vale output

As a technical writer, you typically run `vale` on the command-line against a content file:

----
$ cd openshift-docs/logging/troubleshooting/
$ vale cluster-logging-troubleshooting-for-critical-alerts.adoc
----

The resulting command output gives you a list of suggestions, warnings, and errors based on customizable styles and vocabulary.

As a writer, you review the output, decide which issues are valid, and update your content accordingly.

.`vale` command line output example
====
++++
<pre>
238:27 <font color="#CC0000">error</font>      Did you really mean        Vale.Spelling       
                    &apos;rebalancing&apos;?                                      
244:6  <font color="#3465A4">suggestion</font> Verify your use of &apos;there  IBM.Usage           
                  are&apos; with the word usage                            
                  guidelines.                                         
244:38 <font color="#C4A000">warning</font>    Consider using &apos;available&apos; CheDocs.CommonTerms
                  rather than &apos;present&apos;
</pre>
++++
====

== Understanding the `vale` command line tool output presentation:

First column::
The line and character number of the issue, such as: `244:6`.

Second column:: 
The alert level, such as `error`, `suggestion`, or `warning`. See: xref:#understanding-vale-alert-levels_{context}[Understanding Vale alert levels]

Third column:: 
The rule message, such as: `Verify your use of 'there are'`

Fourth column::
The name of the style and of the rule, such as: `IBM.Usage`.

[id="understanding-vale-alert-levels_{context}"]
== Understanding Vale alert levels

error::
Fix the language error. This alert level includes spelling errors, which are frequently happening on products and tools names. In that case, consider extending the Vocabulary. See xref:extending-the-vocabulary.adoc[].

warning::
Consider fixing the language error.

suggestion::
Heads up! Verify the usage depending on the context. Content containing suggestions is fine.

.Additional resources

* xref:defining-a-vale-onboarding-strategy.adoc[]
* xref:extending-the-vocabulary.adoc[].
* xref:extending-styles.adoc[].


