:_module-type: PROCEDURE

[id="proc_using-vale-with-a-continuous-integration-service_{context}"]
= Using vale with a continuous integration service

Consider using the vale CLI with a continuous integration service when:

* The goal is to measure or enforce the project compliance with the Style Guides.
* xref:using-vale-github-action.adoc[] is not an option.


.Prerequisites

* xref:getting-started-with-vale.adoc[]
* xref:adding-vale-configuration-to-a-project.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]

.Procedure

. Configure your continuous integration service to download the `vale` CLI, the _RedHat_ style and the Vale configuration file using a `download_vale.sh` script such as:
+
[source,bash]
----
include::example$download_vale.sh[]
----


. Configure your continuous integration service to validate language changes using a `validate_language_changes.sh` script such as:
+
[source,bash]
----
include::example$validate_language_changes.sh[]
----

.Additional resources

* link:https://docs.errata.ai/vale/install#using-vale-with-a-continuous-integration-ci-service[Add Vale to your docs continuous integration (CI) service].
