:_module-type: REFERENCE

[id="ref_defining-a-vale-onboarding-strategy_{context}"]
= Defining a vale onboarding strategy

Embracing a linter in a project is a long journey. The full vale report can be discouraging at first. Remember that:

* You are in charge: review the report and decide what is useful to you. 
* The styles are not perfect or complete. 
* Assess the maturity of the project

.Prerequisites
 
* xref:reporting-vale-alerts.adoc[]
* xref:understanding-vale-output.adoc[]

== Assess the project maturity

Zero vale errors::
The project is compliant with the `RedHat` style. Consider integration with a continuous integration service using the defaults from the `{repository-name}` repository.

* xref:using-vale-github-action.adoc[]
* xref:using-vale-with-a-continuous-integration-service.adoc[]

Under 100 Vale errors::
The project is almost compliant with the `RedHat` style. Consider integration with a continuous integration service using the defaults from the `{repository-name}` repository. Consider massively fixing the few errors.

Over 100 Vale errors::
The project is big or poorly compliant with the `RedHat` style. Consider further investigation to understand the issue. 

== Fix the alerts

* Run campaigns focused on one target such as: fix all errors, fix all occurrences of a given rule.

* Disable a rule that is irrelevant in the file context. See: link:https://docs.errata.ai/vale/scoping[Vale - Scoping]
+
----
pass:[<!-- vale RedHat.Spelling = NO -->]

The Spelling rule is ignored for this line.

pass:[<!-- vale RedHat.Spelling = YES -->]

The Spelling rule is active for this line.

----

== Display less alerts without changing the configuration file


* Display only *errors*. Don't display *warnings* and *suggestions*.
+
----
$ vale --minAlertLevel=error .
----

* Display only *errors* and *warnings*. Don't display *suggestions*.
+
----
$ vale --minAlertLevel=warning .
----


== Contributing to the _{repository-name}_ repository

* xref:contributor-guide:extending-the-spelling-rule.adoc[]

* xref:contributor-guide:extending-the-redhat-style.adoc[]

== Decrease the number of alerts requesting xref:adding-vale-configuration-to-a-project.adoc[]

* xref:creating-a-vocabulary-for-a-project.adoc[]

* Altering *rules* severity or disabling *rules* for the project. See xref:adding-vale-configuration-to-a-project.adoc[] and link:https://docs.errata.ai/vale/config[Vale documentation - configuration].
+
----
RedHat.Annotations = NO
RedHat.Slash = warning
RedHat.Usage = suggestion
----

* Creating an additional style for the project. See xref:adding-vale-configuration-to-a-project.adoc[]


[role="_additional-resources"]
.Additional resources

* xref:getting-started-with-vale.adoc[]
* xref:understanding-vale-output.adoc[]

