:_module-type: PROCEDURE

[id="proc_creating-a-vocabulary-for-a-project_{context}"]
= Creating a vocabulary for a project

Consider adding a *Vocabulary* to your project when: 

* Missing words in the Vale dictionary are causing *Spelling* errors
* The word is too specific to benefit to other projects.

When adding the word will benefit to other projects, consider xref:contributor-guide:extending-the-spelling-rule.adoc[]. For example: product and tool names, common terms specific to the software industry. 

.Prerequisites

* xref:installing-vale-cli.adoc[]
* xref:understanding-vale-output.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]

.Procedure

* Create or edit the Vocabulary for your project: create or edit the `.vale/styles/Vocab/__<Project>__/accept.txt` file and add the missing word. Ensure the entry is not case-sensitive.
+
.Entry in the vocabulary, not case-sensitive
----
[Pp]odman
----


* Register the Vocabulary in the `.vale.ini` file
+
[source,ini,subs="+quotes,+attributes,+macros"]
----
Vocab = __<Project>__
----

.Verification

* Run the `vale` command on a content file containing the word which was missing.
+
[subs="+quotes,+attributes"]
----
$ cd __<project_directory>__
$ vale __<filename>__
----

.Additional resources

* link:https://vale.sh/docs/topics/vocab[Vale documentation - Vocabularies]

