:_content-type: PROCEDURE

[id="proc_gitlab-c_{context}"]
= Enabling style compliance reports in GitLab merge requests

[role="_abstract"]
This procedure enables the GitLab Code Quality widget for Vale.
The widget reports style compliance issues in the GitLab merge request interface.

.Prerequisites

* xref:introduction.adoc[]
* xref:adding-vale-configuration-to-a-project.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]

.Procedure

. Create a `.gitlab-ci.yml` file at the repository root with the following content:
+
[source,yaml]
----
include::https://raw.githubusercontent.com/redhat-documentation/vale-at-red-hat/main/tools/.gitlab-ci.yml[]
----

. Create a `vale-json.tmpl` file at the repository root:
+
[source,tmpl]
----
include::https://raw.githubusercontent.com/redhat-documentation/vale-at-red-hat/main/tools/vale-json.tmpl[]
----

. Add the following entries to `.gitignore`:
+
[source]
----
.vale
gl-code-quality-report.json
----

. Commit the files to the local repository:
+
[source]
----
git add .
git commit -m "Add GitLab CI/CD code quality pipeline"
----

. Push the changes to the remote repository:
+
[source]
----
git push -u origin main
----

Once merged, a code quality pipeline runs for every new commit added in a PR. Access the report from the **Pipelines** menu item in the GitLab repository.

[role="_additional-resources"]
.Additional resources
* For more details on GitLab's Code Quality feature, see the link:https://docs.gitlab.com/ee/user/project/merge_requests/code_quality.html[GitLab Docs].
