// Metadata for Antora
:navtitle: Adding Vale to a project
:keywords: vale
:page-aliases: end-user-guide:adding-vale-configuration-to-a-project.adoc
:description: Describes Vale configuration for your project

// End of metadata for Antora
:_module-type: PROCEDURE
:context: adding-vale-configuration-to-a-project
[id="proc_adding-vale-configuration-to-a-project_{context}"]
= Adding Vale to a project

Consider adding Vale configuration files to a project to:

* Simplify Vale usage by anyone in a project
* Use Vale in continuous integration

.Prerequisites

* Install the Vale command-line tool.

.Procedure

. Copy the following recommended Vale at Red Hat `.vale.ini` file to the root directory for your documentation project:
+
.Recommended .vale.ini
[source,ini]
----
# Vale configuration file for the https://github.com/redhat-documentation/vale-at-red-hat repository.
# See: https://docs.errata.ai/vale/config

# The relative path to the folder containing linting rules (styles).
StylesPath = .vale/styles

# Optional: Use the `Vocab` parameter to define exceptions to the ruleset specified for `BasedOnStyles`.
# For more information about how to use the `Vocab` feature of vale, see: https://docs.errata.ai/vale/vocab

# Minimum alert level
# -------------------
# The minimum alert level in the output (suggestion, warning, or error).
# If integrated into CI, builds fail by default on error-level alerts, unless you run Vale with the --no-exit flag
MinAlertLevel = suggestion

# IgnoredScopes specifies inline-level HTML tags to ignore.
# These tags may occur in an active scope (unlike SkippedScopes, skipped entirely) but their content still will not raise any alerts.
# Default: ignore `code` and `tt`.
IgnoredScopes = code, tt, img, url, a, body.id
# SkippedScopes specifies block-level HTML tags to ignore. Ignore any content in these scopes.
# Default: ignore `script`, `style`, `pre`, and `figure`.
# For AsciiDoc: by default, listingblock, and literalblock.
SkippedScopes = script, style, pre, figure, code, tt, blockquote, listingblock, literalblock

[formats]
# Associate `*.properties` files with the `md` format
properties = md

# Match AsciiDoc files. See: https://docs.errata.ai/vale/scoping
# Ignore files in a directory starting by `.`
# to avoid raising errors for `.vale/fixtures/*/testinvalid.adoc` files
[[!.]*.adoc]
# Styles to load, located in the `StylesPath` folder:
BasedOnStyles = RedHat
; Ignore attributes definition, id statements
TokenIgnores = (:[^\n]+: [^\n]+), (\[id=[^\n]+)

; RedHat.BareMetal = NO


# Match Markdown files. See: https://docs.errata.ai/vale/scoping
# Match also `*.properties` files (see the `format` section).
[*.md]
# Styles to load, located in the `StylesPath` folder:
BasedOnStyles = RedHat

# Ignore code surrounded by backticks or plus sign, parameters defaults, URLs.
TokenIgnores = (\x60[^\n\x60]+\x60), ([^\n]+=[^\n]*), (\+[^\n]+\+), (http[^\n]+\[)

# Match Restructured text files
[*.rst]
# Styles to load, located in the `StylesPath` folder:
BasedOnStyles = RedHat

# Match INI files. See: https://docs.errata.ai/vale/scoping
[*.ini]
# Styles to load, located in the `StylesPath` folder:
BasedOnStyles = RedHat
# Ignore code surrounded by backticks or plus sign, parameters defaults, URLs.
TokenIgnores = (\x60[^\n\x60]+\x60), ([^\n]+=[^\n]*), (\+[^\n]+\+), (http[^\n]+\[)
# Disabling rules (NO)
RedHat.CaseSensitiveTerms = NO
RedHat.ConfigMap = NO
RedHat.Definitions = NO
RedHat.Slash = NO
RedHat.Spacing = NO
RedHat.Spelling = NO
RedHat.TermsSuggestions = NO
----
+
[NOTE]
====
By default, the `.vale.ini` file sets `MinAlertLevel = suggestion`.
Consider changing `MinAlertLevel` to `warning` or `error` for new projects.
====

* Run the `vale sync` command from the repository folder to download the rules to the project directory. For example:
+
[source,terminal]
----
$ cd {repository-name}
$ vale sync
 SUCCESS  Downloaded package 'RedHat'
Downloading packages [1/1]
----

.Verification

* Run the `vale` command on one of your content files.
+
[source,console,subs="+quotes,+attributes"]
----
$ cd __<project_directory>__
$ vale __<filename>__
----

.Additional resources

* xref:defining-a-vale-onboarding-strategy.adoc[]
