// Metadata for Antora
:navtitle: Adding Vale to a project
:keywords: vale
:page-aliases: end-user-guide:adding-vale-configuration-to-a-project.adoc
:description: Describes Vale configuration for your project

// End of metadata for Antora
:_module-type: PROCEDURE
:context: adding-vale-configuration-to-a-project
[id="proc_adding-vale-configuration-to-a-project_{context}"]
= Adding Vale to a project

Consider adding Vale configuration files to a project to:

* Add project-specific rules
* Simplify Vale usage by anyone in a project
* Use Vale in continuous integration

.Prerequisites

* Install the Vale command-line tool.

.Procedure

. Copy the following recommended Vale at Red Hat `.vale.ini` file to the root directory for your documentation project:
+
.Recommended .vale.ini
[source,ini]
----
include::https://raw.githubusercontent.com/redhat-documentation/vale-at-red-hat/main/.vale.ini[]
----
+
[NOTE]
====
By default, the `.vale.ini` file sets `MinAlertLevel = suggestion`.
Consider changing `MinAlertLevel` to `warning` or `error` for new projects.
====

* Run the `vale sync` command from the repository folder to download the rules to the project directory. For example:
+
[source,terminal]
----
$ cd {repository-name}
$ vale sync
 SUCCESS  Downloaded package 'RedHat'
Downloading packages [1/1]
----

.Verification

* Run the `vale` command on one of your content files.
+
[source,console,subs="+quotes,+attributes"]
----
$ cd __<project_directory>__
$ vale __<filename>__
----

.Additional resources

* xref:defining-a-vale-onboarding-strategy.adoc[]
