// Metadata for Antora
:navtitle: Adding Vale to a project
:keywords: vale
:page-aliases: end-user-guide:adding-vale-configuration-to-a-project.adoc
:description: Describes Vale configuration for your project

// End of metadata for Antora
:_module-type: PROCEDURE
:context: adding-vale-configuration-to-a-project
[id="proc_adding-vale-configuration-to-a-project_{context}"]
= Adding Vale to a project

Consider adding Vale configuration files to a project to:

* Simplify Vale usage by anyone in a project
* Use Vale in continuous integration

.Prerequisites

* Install the Vale command-line tool.

.Procedure

. Create a `.vale.ini` configuration file in the root directory for your documentation project:
+
.Example .vale.ini
[source,ini]
----
# The relative path to the folder containing linting rules (styles).
StylesPath = .vale/styles

MinAlertLevel = suggestion

SkippedScopes = script, style, pre, figure, code, tt, blockquote, listingblock, literalblock

[formats]
# Associate `*.properties` files with the `md` format
properties = md

[*.adoc]
# Styles to load, located in the `StylesPath` folder:
BasedOnStyles = RedHat

# Ignore attributes definition, id statements
TokenIgnores = (:[^\n]+: [^\n]+), (\[id=[^\n]+)

[*.md]
BasedOnStyles = RedHat

# Ignore code surrounded by backticks or plus sign, parameters defaults, URLs.
TokenIgnores = (\x60[^\n\x60]+\x60), ([^\n]+=[^\n]*), (\+[^\n]+\+), (http[^\n]+\[)

# Match INI files. See: https://docs.errata.ai/vale/scoping
[*.ini]
BasedOnStyles = RedHat
# Ignore code surrounded by backticks or plus sign, parameters defaults, URLs.
TokenIgnores = (\x60[^\n\x60]+\x60), ([^\n]+=[^\n]*), (\+[^\n]+\+), (http[^\n]+\[)

# Disabling rules (NO)
RedHat.CaseSensitiveTerms = NO
RedHat.ConfigMap = NO
RedHat.Definitions = NO
RedHat.Slash = NO
RedHat.Spacing = NO
RedHat.Spelling = NO
RedHat.TermsSuggestions = NO
----
+
[NOTE]
====
By default, the `.vale.ini` file sets `MinAlertLevel = suggestion`.
Consider changing `MinAlertLevel` to `warning` or `error` for new projects.
For a complete list of possible configuration options, see link:https://vale.sh/docs/topics/config#config-file[Configuration options for .vale.ini]
====

* Run the `vale sync` command from the repository folder to download the rules to the project directory. For example:
+
[source,terminal]
----
$ cd __<project_directory>__
$ vale sync
 SUCCESS  Downloaded package 'RedHat'
Downloading packages [1/1]
----

.Verification

* Run the `vale` command on one of your content files.
+
[source,console,subs="+quotes,+attributes"]
----
$ cd __<project_directory>__
$ vale __<filename>__
----

.Additional resources

* xref:defining-a-vale-onboarding-strategy.adoc[]
