// Metadata for Antora
:navtitle: Collating Vale output
:keywords: collating, output
:description: Collating the Vale CLI report results
:page-aliases: end-user-guide:collating-vale-output.adoc
// End of metadata for Antor


:_module-type: CONCEPT
[id="collating-vale-output"]
= Collating Vale output

You can use a template to collate the results from running `vale` on the command line. This collated output is non-repetitive and might be easier to use.

The `RedHat` style includes a `collate-output.tmpl` template you can specify when you run the `vale` command. For example:

----
$ cd openshift-docs/
$ vale --output='.vale/styles/RedHat/collate-output.tmpl' modules/about-crio.adoc
----

The resulting command output collates any repetitive the suggestions, warnings, or errors.

.Example `vale` output from the `collate-output.tmpl` template
----
 modules/about-crio.adoc

 7:9,11:107  suggestion  Define acronyms and             RedHat.Definitions
                         abbreviations (such as 'CRI')
                         on first occurrence if they're
                         likely to be unfamiliar.

0 errors, 0 warnings and 2 suggestions in 1 file.
----

[NOTE]
====
When you use the `--output` option, other options such as `--minAlertLevel` might not work.
====

[id="understanding-vale-alert-levels"]
== Understanding the `vale` output

First column::
A comma-separated list of each instance where the issue appears: `7:9,11:107`.

Second column::
The alert level, such as `error`, `suggestion`, or `warning`. See: xref:#understanding-vale-alert-levels[Understanding Vale alert levels]

Third column::
The rule message, such as: `Define acronyms and abbreviations (such as 'CRI') on first occurrence if they're likely to be unfamiliar.`

Fourth column::
The name of the style and rule, such as: `RedHat.Definitions`.

.Additional resources

* xref:understanding-vale-output.adoc[]
* link:https://vale.sh/manual/output/[The `--output` topic in the Vale manual]
