// Metadata for Antora
:navtitle: GitLab Code Quality reports
:keywords: vale gitlab
:description: How to use GitLab code quality reports
// :page-aliases: 
// End of metadata for Antora
[id="configuring-vale-for-gitlab-code-quality-reports"]
= GitLab Code Quality reports

[id="proc_gitlab-c"]
== Enabling style compliance reports in GitLab merge requests

Use this procedure to enable the GitLab Code Quality widget for Vale.
The widget reports style compliance issues in the GitLab merge request interface.

.Prerequisites

* xref:introduction.adoc[]
* xref:adding-vale-configuration-to-a-project.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]

.Procedure

. Create a `.gitlab-ci.yml` file at the repository root with the following content:
+
[source,yaml]
----
include::example$gitlab-ci.yml[]
----

. Create a `vale-json.tmpl` file at the repository root:
+
[source,tmpl]
----
include::example$vale-json.tmpl[]
----

. Add the following entries to `.gitignore`:
+
[source]
----
.vale
gl-code-quality-report.json
----

. Commit the files to the local repository:
+
[source]
----
git add .
git commit -m "Add GitLab CI/CD code quality pipeline"
----

. Push the changes to the remote repository:
+
[source]
----
git push -u origin main
----

When you merge the changes to the main branch, a code quality pipeline will run for every new commit added in a merge request. The code quality report is available in the Merge Request **Overview** tab.

[NOTE]
====
The GitLab CI job creates the code quality report by comparing a complete list of errors in the main branch and a list of errors in the merge request branch.
This might cause a CI bottleneck on large repositories with 1000s of files, but for small and medium repositories, the CI processing time is negligible.
====

[role="_additional-resources"]
.Additional resources
* For more details on GitLab's Code Quality feature, see the link:https://docs.gitlab.com/ee/ci/testing/code_quality.html[Code Quality].
