// Metadata for Antora
:navtitle: Installing Vale
:keywords: vale
:description: Describes how to install from the latest release and configure the Vale CLI
:page-aliases: end-user-guide:using-vale-cli.adoc, installing-vale-cli-from-zip.adoc
// End of metadata for Antora
[id="proc_installing-vale-cli"]
= Installing Vale with the RedHat package system-wide

To use Vale CLI with the `RedHat` style for all folders and projects, install and configure Vale CLI version 2.16.0 or later and create a `.vale.ini` configuration file.

[IMPORTANT]
====
If you are installing Vale for use with a project that already has a Vale configuration, all you need to do is install the Vale command-line tool and run `vale sync` from the project folder.
====

.Prerequisites

* You've installed a recent release of the link:https://docs.asciidoctor.org/asciidoctor/latest/install/[Asciidoctor] Ruby gem on your system.

.Procedure

. Install the Vale command-line tool on your workstation. On RHEL or Fedora systems, run the following command:
+
[source,terminal]
----
$ sudo dnf copr enable mczernek/vale && sudo dnf install vale
----
+
[NOTE]
For other operating systems, see link:https://vale.sh/docs/vale-cli/installation/[Installing Vale].

. Create a `.vale.ini` configuration file and save it in your `$HOME` directory.
+
.Example .vale.ini
[source,ini]
----
include::example$vale.ini[]
----
+
[TIP]
====
You can have multiple `.vale.ini` files for different projects.
`.vale.ini` files that are lower in the folder structure override higher level files.

See link:https://vale.sh/docs/topics/config[Vale configuration reference] for more information.
====

. Download the rules:
+
[source,console]
----
$ vale sync
----
+
.Example output
[source,terminal]
----
$ vale sync
 SUCCESS  Downloaded package 'RedHat'
Downloading packages [1/1]
----
+
[TIP]
Run the `vale sync` command periodically to update the `RedHat` Vale package.

.Verification

. Run `vale` against a source file:
+
[source,console,subs="+quotes,+attributes"]
----
$ cd __<project_directory>__
$ vale __<filename>__
----
+
.Example output
[source,terminal]
----
$ vale modules/ztp-creating-the-site-secrets.adoc

 modules/ztp-creating-the-site-secrets.adoc
 10:222  error       Use 'Assisted Installer'        Vale.Terms
                     instead of 'assisted
                     installer'.
 14:13   suggestion  'are referenced' is passive     RedHat.PassiveVoice
                     voice. In general, use active
                     voice. Consult the style guide
                     for acceptable use of passive
                     voice.

✖ 1 error, 0 warnings and 1 suggestions in 1 file.
----

.Additional resources
* xref:understanding-vale-output.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]
* link:https://vale.sh/docs/vale-cli/installation/[Installing Vale CLI]
* link:https://vale.sh/docs/topics/config[Configuring Vale CLI]
* link:https://marketplace.visualstudio.com/items?itemName=errata-ai.vale-server[VS Code + Vale]
* link:https://plugins.jetbrains.com/plugin/19613-vale-cli[Intellijel IDE + Vale]
* link:https://packagecontrol.io/packages/LSP-vale-ls[Sublime Text + Vale]
* link:https://vale.sh/generator[Vale configuration generator]
