// Metadata for Antora
:navtitle: Installing Vale
:keywords: vale
:description: Describes how to install from the latest release and configure the Vale CLI
:page-aliases: end-user-guide:using-vale-cli.adoc, installing-vale-cli-from-zip.adoc
// End of metadata for Antora
// Metadata for Modular Docs
:context: assembly_getting-started-with-vale
:_module-type: PROCEDURE
// End of metadata for Modular Docs
[id="proc_installing-vale-cli_{context}"]
= Installing Vale with the `RedHat` package system-wide

To use Vale CLI with the `RedHat` style on any project without further configuration in the projects: install and configure Vale CLI version 2.16.0 or later.

[IMPORTANT]
====
If you are installing Vale for use with a project that already has a Vale configuration, all you need to do is install the Vale command-line tool and run `vale sync` from the project folder.
====

.Prerequisites

* You've installed a recent release of the link:https://docs.asciidoctor.org/asciidoctor/latest/install/[Asciidoctor] Ruby gem on your system.

.Procedure

. Install the Vale command-line tool on your workstation. On RHEL or Fedora systems, run the following command:
+
[source,terminal]
----
$ sudo dnf copr enable mczernek/vale && sudo dnf install vale
----
+
[NOTE]
Alternatively, see link:https://vale.sh/docs/vale-cli/installation/[Installing Vale].
On the Vale site, click the tab for your operating system.

. Add the `RedHat` Vale package in the `.vale.ini` Vale configuration file. Save the file in your `$HOME` directory:
+
.Example .vale.ini
[source,ini]
----
StylesPath = styles

MinAlertLevel = suggestion

Packages = RedHat

[*]
BasedOnStyles = RedHat
----
+
[TIP]
Some projects require a specific Vale configuration.
Consider saving the `.vale.ini` file at the root of the project.
See link:https://vale.sh/docs/topics/config[Vale configuration reference].

. Get the `RedHat` Vale package.
+
[source,console]
----
$ vale sync
----
+
[TIP]
Run the `vale sync` command periodically to update the `RedHat` Vale package.

.Verification

. Enter the `vale` command on one of your content files.
+
[source,console,subs="+quotes,+attributes"]
----
$ cd __<project_directory>__
$ vale __<filename>__
----

. Review the vale output and use it to update your content file.

. Re-enter the same `vale` command to see the updated results.

.Additional resources
* xref:understanding-vale-output.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]
* link:https://vale.sh/docs/vale-cli/installation/[Installing Vale CLI]
* link:https://vale.sh/docs/topics/config[Configuring Vale CLI]
* link:https://marketplace.visualstudio.com/items?itemName=errata-ai.vale-server[VS Code + Vale]
* link:https://plugins.jetbrains.com/plugin/19613-vale-cli[Intellijel IDE + Vale]
* link:https://packagecontrol.io/packages/LSP-vale-ls[Sublime Text + Vale]
* link:https://vale.sh/generator[Vale configuration generator]
