// Metadata for Antora
:navtitle: Installing Vale
:keywords: vale
:description: Describes how to install from the latest release and configure the Vale CLI
:page-aliases: end-user-guide:using-vale-cli.adoc, installing-vale-cli-from-zip.adoc
// End of metadata for Antora
[id="proc_installing-vale-cli"]
= Installing Vale and the RedHat package

Install the Vale linter and the `RedHat` package to automate reviewing content for style and structure.

[IMPORTANT]
====
Vale v3.0.0+ introduces a breaking change in how the Styles path is configured.
Until we reconcile these changes, use Vale v2.30.0 or lower.
====

.Prerequisites

* Install the link:https://docs.asciidoctor.org/asciidoctor/latest/install/[Asciidoctor] Ruby gem.

* Remove any previously installed `mczernek/vale` RPM installation. Fedora 39 CSB is not compatible with the latest `mczernek/vale` RPM.
To remove a previous Vale RPM installation, do the following:
+
[source,terminal]
----
sudo dnf remove vale
----

.Procedure

. To install the Vale v2.30.0 command-line tool on RHEL or Fedora, run the following commands:
+
[source,terminal]
----
wget https://github.com/errata-ai/vale/releases/download/v2.30.0/vale_2.30.0_Linux_64-bit.tar.gz

tar xzvf vale_2.30.0_Linux_64-bit.tar.gz vale -C ${HOME}/bin

echo "Installed $(vale --version) to ${HOME}/bin/vale"
----
+
[NOTE]
For other operating systems, see link:https://vale.sh/docs/vale-cli/installation/[Installing Vale].

. To use Vale with the `RedHat` package system-wide, create the following `.vale.ini` configuration file in your `$HOME` directory.
+
.Example .vale.ini
[source,ini]
----
include::example$vale.ini[]
----
+
[TIP]
====
Some product documentation repositories, such as `openshift-docs`, have a  `.vale.ini` file. When you run `vale` on content files in the repository directory, the `<repository>/.vale.ini` file overrides the `$HOME/.vale.ini` file. For more information, see link:https://vale.sh/docs/topics/config[Vale configuration reference].
====

. Download the `RedHat` package to your computer.
+
[source,console]
----
$ vale sync
----
+
.Example output
[source,terminal]
----
$ vale sync
 SUCCESS  Downloaded package 'RedHat'
Downloading packages [1/1]
----
+
[TIP]
To get the latest updates, run `vale sync` regularly.

.Verification

. Run `vale` against a source file:
+
[source,console,subs="+quotes,+attributes"]
----
$ cd __<project_directory>__
$ vale __<filename>__
----
+
.Example output
[source,terminal]
----
$ vale modules/ztp-creating-the-site-secrets.adoc

 modules/ztp-creating-the-site-secrets.adoc
 10:222  error       Use 'Assisted Installer'        Vale.Terms
                     instead of 'assisted
                     installer'.
 14:13   suggestion  'are referenced' is passive     RedHat.PassiveVoice
                     voice. In general, use active
                     voice. Consult the style guide
                     for acceptable use of passive
                     voice.

✖ 2 errors, 0 warnings and 1 suggestion in 1 file.
----

.Additional resources
* xref:understanding-vale-output.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]
* link:https://vale.sh/docs/vale-cli/installation/[Installing Vale CLI]
* link:https://vale.sh/docs/topics/config[Configuring Vale CLI]
* link:https://marketplace.visualstudio.com/items?itemName=ChrisChinchilla.vale-vscode[Install the Visual Studio Code extension for Vale, "Vale VSCode"] (Important: This new extension replaces the deprecated "vale-server" extension.)
* link:https://plugins.jetbrains.com/plugin/19613-vale-cli[Intellijel IDE + Vale]
* link:https://packagecontrol.io/packages/LSP-vale-ls[Sublime Text + Vale]
* link:https://vale.sh/generator[Vale configuration generator]
