// Metadata for Antora
:navtitle: OpenShift AsciiDoc style
:keywords: openshift-asciidoc-style-for-vale, antora
:description: Get started with the OpenShiftAsciiDoc style for Vale
// End of metadata for Antora
:_module-type: CONCEPT
[id="asciidoc-style-for-vale"]
= OpenShift AsciiDoc style for Vale

The `OpenShiftAsciiDoc` style for Vale consists of rules suitable for OpenShift documentation projects written in AsciiDoc.
It lints common OpenShift AsciiDoc syntax errors as outlined in link:https://github.com/openshift/openshift-docs/blob/main/contributing_to_docs/doc_guidelines.adoc#documentation-guidelines[OpenShift documentation guidelines]
Use the OpenShiftAsciiDoc style in conjunction with other Vale styles.

Some of the errors that the `OpenShiftAsciiDoc` rules highlight include:

* `:_additional-resources:` role attribute declaration
* Terminal code block missing a shell prompt symbol (`$`)  at the beginning of the line
* Missing `.Example output` title for example listing blocks
* ID missing the `++{_context}++` variable at the end of the ID
* modules missing the `:_content-type:` variable
* Cross references (`xref`) missing anchor IDs
* Cross references that use `.adoc` instead of `.html` for links
* Cross references missing link alt text

[IMPORTANT]
====
These rules are suitable for AsciiDoc source files only.
====

To use the `OpenShiftAsciiDoc` style, do the following:

. Update your project `.vale.ini` to include the the `OpenShiftAsciiDoc` style. Add `OpenShiftAsciiDoc` to the `Packages` and `BasedOnStyles` fields. For example:
+
.Example .vale.ini
[source,ini]
----
StylesPath = .vale/styles

MinAlertLevel = suggestion

Packages = RedHat, OpenShiftAsciiDoc

# Ignore files in dirs starting with `.` to avoid raising errors for `.vale/fixtures/*/testinvalid.adoc` files
[[!.]*.adoc]
BasedOnStyles = RedHat, OpenShiftAsciiDoc
----
+
[NOTE]
====
Some rules are applicable to modules only.
To use a different set of rules for modules and assemblies, create two `.vale.ini` files, one in the project root, and one in the `/modules` folder.
For the root `.vale.ini` file, add the following to disable rules that don't apply to assemblies:

[source,ini]
----
# Disable module specific rules
OpenShiftAsciiDoc.ModuleContainsParentAssemblyComment = NO
OpenShiftAsciiDoc.NoNestingInModules = NO
OpenShiftAsciiDoc.NoXrefInModules = NO
----
====

. Sync your project that contains the updated `.vale.ini` configuration, for example:

.. Open a shell prompt and change to the project directory:
+
[source,terminal]
----
$ cd <project_dir>
----

.. Run the sync command to pull the new Rule packages
+
[source,terminal]
----
$ vale sync
----
+
.Example output
[source,terminal]
----
 SUCCESS  Downloaded package 'RedHat'
 SUCCESS  Downloaded package 'OpenShiftAsciiDoc'
Downloading packages [2/2] ██████████████████ 100% | 3s
----

The xref:contributor-guide:vale-at-red-hat-repository.adoc[] contains the `OpenShiftAsciiDoc` style in the following directory:

----
.vale/styles/OpenShiftAsciiDoc
----

[role="_additional-resources"]
.Additional resources
* xref:installing-vale-cli.adoc[]
* xref:using-vale-in-the-ide.adoc[]
* xref:using-vale-github-action.adoc[]
* xref:adding-vale-configuration-to-a-project.adoc[]
