// Metadata for Antora
:navtitle: RedHat style
:keywords: redhat-style-for-vale, antora
:description: Get started with the Red Hat style for Vale
:page-aliases: end-user-guide:redhat-style-for-vale.adoc
// End of metadata for Antora
:_module-type: CONCEPT
[id="redhat-style-for-vale"]
= Red Hat style for Vale

The `RedHat` style for Vale consists of language rules suitable for documentation in Open Source projects and mandatory for Red Hat products.
The Red Hat language rules originate from:

* link:{ssg-url}[_{ssg}_]
* Latest edition of the _{ibmsg}_
* link:https://github.com/errata-ai/IBM[Vale-compatible implementation] of link:https://www.ibm.com/developerworks/library/styleguidelines/index.html[_IBM Developer Editorial Style Guide_]
* link:{valedict-url}[_{valedict}_]

[IMPORTANT]
====
The `RedHat` style for Vale is compatible with Vale version 3.7 and above.

Vale v3 introduced a breaking change for the Vale vocabulary folder location.
For Vale v3+, if you use a vocabulary with your project, ensure that the vocabulary folder matches this folder structure:

[source,terminal]
----
.vale/styles/config/vocabularies/<project_vocab_folder>
----

For more information see, link:https://vale.sh/docs/topics/vocab/[Vocabularies].
====

[role="_additional-resources"]
.Additional resources
* xref:installing-vale-cli.adoc[]
* xref:using-vale-in-the-ide.adoc[]
* xref:using-vale-github-action.adoc[]
* xref:adding-vale-configuration-to-a-project.adoc[]
