// Metadata for Antora
:navtitle: Vale reports
:keywords: reporting
:description: Describes how to generate Vale reports
// End of metadata for Antora

:context: generating-extended-vale-alerts-reports
:_module-type: PROCEDURE
[id="generating-extended-vale-alerts-reports_{context}"]
= Generating extended Vale alerts reports

Consider generating extended Vale alerts reports about a Git repository to:

* Measure language compliance in a repository
* Gather data before xref:defining-a-vale-onboarding-strategy.adoc[]

These reports use the Vale report in JSON format and additional information such as the word count.

On bigger repositories, with more than 1000000 words, consider building your own reporting tool to chunk the task in smaller pieces.

.Prerequisites

* The `vale` tool is installed and configured. See xref:installing-vale-cli.adoc[].
* The `jq` tool is installed. See link:https://stedolan.github.io/jq/download/[Downloading `jq`].

.Procedure


. Generate vale alerts reports for _<location>_:
+
[subs="+quotes,+attributes"]
----
$ ./tools/vale_report.sh _<location>_
----

. The script creates following files for each Git repository found at _<location>_:
+
`vale-report_<repository>_-list.log`:: List of AsciiDoc files considered for the report.
`vale-report_<repository>_-wordcount.log`:: Word count for all files in the file list. Use this information to compare the number of alerts between repositories.
`vale-report_<repository>_.json`:: Vale report in JSON format. Use the `jq` tool to query the results.
`vale-report_<repository>_.severity`:: Breakdown of alerts by severity.
`vale-report_<repository>_.rules`:: Breakdown of alerts by rules.
`vale-report_<repository>_.Spelling.txt`:: Breakdown of `Spelling` alerts.

.Additional resources

* xref:understanding-vale-output.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]



