// Metadata for Antora
:navtitle: Using the Vale-at-Red-Hat web app
:keywords: vale, app
:description: Quickly get started with Vale and analyze a batch of content by using the Vale-at-Red-Hat online web app.
:page-aliases: end-user-guide:get-started-vale-app.adoc
// End of metadata for Antora
// Metadata for Modular Docs

:_module-type: PROCEDURE
// End of metadata for Modular Docs
[id="proc_using-vale-app"]
= Analyzing your content by using the Vale-at-Red-Hat web app

To get familiar with Vale without installing the Vale software on your local client, you can use the Vale-at-Red-Hat web app. 
This web app is preconfigured to analyze your content by using Red Hat's style rules.

.Prerequisites
* You must have Docker or Podman installed on your system.

.Procedure
. Run the following command to download the image and start the container:
+
[source, terminal]
```bash
docker run --rm -p 8080:8080 quay.io/ganelson/vale-online-app
```
. Open your browser and go to `http://localhost:8080`.
. Paste the content you want to check in the text area and click on the `Lint` button.
+
[[NOTE]]
====
By default, the Vale-at-Red-Hat web app displays warnings and errors only. You can also view suggestions by using the options menu on the left.
====
. To close the app, press `Ctrl+C` in the terminal where the container is running.
