// Metadata for Antora
:navtitle: GitHub Action
:keywords: vale, github
:description: Overview of using Vale in a GitHub Action
:page-aliases: end-user-guide:using-vale-github-action.adoc
// End of metadata for Antora

:context: using-vale-github-action
:_module-type: PROCEDURE
[id="proc_using-vale-github-action_{context}"]
= Using Vale GitHub Action

Consider using Vale GitHub Action when:

* The goal is to measure or enforce the project compliance with the Style Guides.
* The content repository is on GitHub.

WARNING: Due to the GitHub token permissions, this Action can not post annotations to pull requests from forked repositories.

.Prerequisites

* xref:installing-vale-cli.adoc[]
* xref:adding-vale-configuration-to-a-project.adoc[]
* xref:defining-a-vale-onboarding-strategy.adoc[]

.Procedure

. Add a `.github/workflows/vale.yml` file to your repository with following content:
+
[source,yaml]
----
name: Linting with Vale
on:
  - pull_request
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Vale Linter
        uses: errata-ai/vale-action@v1.5.0
        with:
          files: __onlyModified
          onlyAnnotateModifiedLines: true
          styles: https://github.com/redhat-documentation/vale-at-red-hat/releases/latest/download/RedHat.zip
          config: https://raw.githubusercontent.com/redhat-documentation/vale-at-red-hat/master/.vale-for-github-action.ini
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
----

. Create a `.github/styles` directory containing an empty file. The Vale GitHub Action use it to decompress the `RedHat` style.
+
----
$ mkdir .github/styles
$ touch .github/styles/.placeholder
----

.Additional resources

* link:https://github.com/errata-ai/vale-action[Vale GitHub action].
