:_module-type: PROCEDURE
[id="using-vale-cli"]
= Analyzing your content by running Vale from the command line

To analyze your content to see how it aligns with the link:https://redhat-documentation.github.io/supplementary-style-guide/[Red Hat supplementary] and link:https://www.ibm.com/docs/en/ibm-style[IBM] style guides, you can run Vale from the command line.
You can run Vale on individual files or an entire directory.

Vale analyzes the specified content according to the command options and the style preferences that you have specified in your `.vale.ini` configuration file.

.Prerequisites

* You've installed a recent release link:https://vale.sh/docs/vale-cli/installation/[Vale] on your system.
* You've installed a recent release of link:https://docs.asciidoctor.org/asciidoctor/latest/[Asciidoctor] on your system.
* You've xref:user-guide.adoc#installing-vale-cli[installed and configured Vale CLI], setting both `Packages`  and `BasedOnStyles` to  `RedHat` in the `.vale.ini` file.
* You've gotten the latest link:https://github.com/redhat-documentation/vale-at-red-hat[`RedHat`] style by running the `vale sync` command.

.Procedure

. Start a terminal session and go to the content folder containing the files that you want to analyze.
. Enter the `vale` linter command by using the following syntax:
+
[source,console,subs="+quotes,+attributes"]
----
$ vale __<target_file_name>__ --__<option>__ > __<output_file_name>__
----
+
Where:

* `<target_file_name>` is the name of the content file that you want to analyze.
Or use the `*` wildcard to analyze all files in the current folder.
* `<option>` is an option you can use to tailor the alerts or linter output.
For more information, see _Example use cases for running the Vale command_.
* `<output_file_name>` is an option that you can append to the command to pipe the output to a specific file instead of at the command line.

.Verification
Review the list of suggestions, warnings, and errors that Vale outputs to the command line.
See xref:user-guide.adoc#understanding-vale-output[Understanding Vale output].

.Example use cases for running the Vale command

* To verify the style compliance of a file in the current folder called `example.adoc`, enter:
+
[source,console]
----
$ vale example.adoc
----
* To verify the style compliance of all files in the current folder and turn off text wrapping in the command-line output, enter:
+
[source,console]
----
$ vale *.* --no-wrap
----
+
[NOTE]
====
If you are expecting a large quantity of output in the report, use the `--no-wrap` option to make the results easier to read from the command line.
====
* To verify the style compliance of a file named `example.adoc` and remove suggestions from the output to retrieve warnings and errors, enter:
+
[source,console]
----
$ vale example.adoc --minAlertLevel=warning
----
* To verify the style compliance of a file named `example.adoc` and report errors only, enter:
+
[source,console]
----
$ vale example.adoc --minAlertLevel=error
----
* To verify the style compliance of a file named `example.adoc` and output errors only into a file in JSON format, enter:
+
[source,console]
----
$ vale example.adoc --minAlertLevel=error --output="JSON" | tee ~/test.json
----
* To verify the style compliance of a file named `example.adoc` and output errors only into a file in JSON format, enter:
* To get help including a list of valid options for running Vale, enter:
+
[source,console]
----
$ vale --help
----

.Additional resources
xref:user-guide.adoc#using-vale-in-the-ide[Using Vale in the IDE]
