---
name: Validate Vale rules

on:
  pull_request:
    paths:
      - .vale/styles/**/*
      - .vale/fixtures/**/*

jobs:
  validate-rules:
    name: Validate rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Vale and validate rules
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sudo gem install asciidoctor
          gh release download --repo 'errata-ai/vale' --pattern '*Linux_64-bit.tar.gz'
          mkdir bin && tar -xvzf *Linux_64-bit.tar.gz -C bin
          export PATH=./bin:"$PATH"
          vale -v
          python3 tools/build-dictionary.py
          chmod +x tools/validate-vale-rules.sh
          ./tools/validate-vale-rules.sh
